=== d66pak/progs/myperl/partnermap.dtd
<!ELEMENT scalar (#PCDATA)>
<!ELEMENT scalarref (#PCDATA)>
<!ATTLIST scalarref 
	blessed_package CDATA #IMPLIED
 	memory_address CDATA #IMPLIED>
<!ELEMENT arrayref (item*)>
<!ATTLIST arrayref 
	blessed_package CDATA #IMPLIED
 	memory_address CDATA #IMPLIED>
<!ELEMENT hashref (item*)>
<!ATTLIST hashref 
	blessed_package CDATA #IMPLIED
 	memory_address CDATA #IMPLIED>
<!ELEMENT item (#PCDATA|scalar|scalarref|arrayref|hashref)*>
<!ATTLIST item 
	key CDATA #REQUIRED
	defined CDATA #IMPLIED>
<!ELEMENT perldata (scalar|scalarref|arrayref|hashref)*>

=== d66pak/progs/myperl/partnermap.xml
<!DOCTYPE perldata SYSTEM "./partnermap.dtd">
<perldata>
 <hashref memory_address="0x8e3998c">
  <item key="blu">
   <hashref memory_address="0x8e52834">
    <item key="path">/partners/blu/</item>
    <item key="subject">Welcome to Yahoo! Mail and Bluelight.com</item>
   </hashref>
  </item>
  <item key="blue1">
   <hashref memory_address="0x8e52864">
    <item key="path">/partners/blue1/</item>
    <item key="subject">Bienvenido a Correo Yahoo! y Bluelight.com</item>
   </hashref>
  </item>
  <item key="bt-1">
   <hashref memory_address="0x8e75910">
    <item key="TIP-header">66.218.69.16</item>
    <item key="bypass-name-check">1</item>
    <item key="domain">
     <arrayref memory_address="0x8e713e4">
      <item key="0">yahoo.com</item>
      <item key="1">yoyo.com</item>
      <item key="2">demobroadband.com</item>
      <item key="3">btinternet.com</item>
      <item key="4">btopenworld.com</item>
     </arrayref>
    </item>
    <item key="imap-server">
     <hashref memory_address="0x8e71438">
      <item key="btinternet.com">194.73.73.163</item>
      <item key="btopenworld.com">194.73.73.163</item>
      <item key="yahoo.com">martini.corp</item>
     </hashref>
    </item>
    <item key="omitwelcomemessage">1</item>
    <item key="path">/partners/bt/uk/</item>
    <item key="pop-server">
     <hashref memory_address="0x8e71474">
     </hashref>
    </item>
    <item key="quota">S2</item>
    <item key="sender">BT Yahoo! Member Services</item>
    <item key="sender2">BT Yahoo! Member Services</item>
    <item key="subject">Welcome to BT Yahoo!</item>
    <item key="subject-tx-confirm">Email Transfer Confirmation</item>
    <item key="subject-tx-error">Email Transfer Error</item>
    <item key="subject-tx-start">Confirmation and Information</item>
    <item key="subject2">Welcome to BT Yahoo!</item>
    <item key="type">
     <hashref memory_address="0x8e75850">
      <item key="temp">
       <hashref memory_address="0x8e7148c">
        <item key="account">temp</item>
        <item key="quota">D</item>
        <item key="tier">temp</item>
       </hashref>
      </item>
      <item key="uk:plus:bt:pri:core:a">
       <hashref memory_address="0x8e714c8">
        <item key="account">Master</item>
        <item key="path">/partners/bt/uk/tierA/</item>
        <item key="quota">D</item>
        <item key="subject-tx-confirm">Your BT Yahoo! Mailbox</item>
        <item key="subject-tx-error">Email Transfer Error</item>
        <item key="subject-tx-start">Your new BT Yahoo! Mail account</item>
        <item key="tier">A</item>
       </hashref>
      </item>
      <item key="uk:plus:bt:pri:core:b">
       <hashref memory_address="0x8e71534">
        <item key="account">Master</item>
        <item key="path">/partners/bt/uk/tierB/</item>
        <item key="quota">P2</item>
        <item key="subject-tx-confirm">Your BT Yahoo! Mailbox</item>
        <item key="subject-tx-error">Email Transfer Error</item>
        <item key="subject-tx-start">Your new BT Yahoo! Mail account</item>
        <item key="tier">B</item>
       </hashref>
      </item>
      <item key="uk:plus:bt:pri:core:c">
       <hashref memory_address="0x8e71618">
        <item key="account">Master</item>
        <item key="path">/partners/bt/uk/tierC/</item>
        <item key="pop">P</item>
        <item key="quota">P2</item>
        <item key="subject-tx-confirm">Your BT Yahoo! Internet mailbox</item>
        <item key="subject-tx-error">Email Transfer Error</item>
        <item key="subject-tx-start">Your new BT Yahoo! Internet account</item>
        <item key="tier">C</item>
       </hashref>
      </item>
      <item key="uk:plus:bt:pri:core:d">
       <hashref memory_address="0x8e7353c">
        <item key="account">Master</item>
        <item key="path">/partners/bt/uk/tierD/</item>
        <item key="pop">P</item>
        <item key="quota">P2</item>
        <item key="subject-tx-confirm">Your BT Yahoo! Internet mailbox</item>
        <item key="subject-tx-error">Email Transfer Error</item>
        <item key="subject-tx-start">Your new BT Yahoo! Internet account</item>
        <item key="tier">D</item>
       </hashref>
      </item>
      <item key="uk:plus:bt:pri:core:e">
       <hashref memory_address="0x8e7362c">
        <item key="account">Master</item>
        <item key="path">/partners/bt/uk/tierE/</item>
        <item key="pop">P</item>
        <item key="quota">P2</item>
        <item key="subject-tx-confirm">Your BT Yahoo! Broadband mailbox</item>
        <item key="subject-tx-error">Email Transfer Error</item>
        <item key="subject-tx-start">Your new BT Yahoo! Broadband account</item>
        <item key="tier">E</item>
       </hashref>
      </item>
      <item key="uk:plus:bt:pri:core:g">
       <hashref memory_address="0x8e7371c">
        <item key="account">Master</item>
        <item key="path">/partners/bt/uk/tierG/</item>
        <item key="quota">P2</item>
        <item key="subject-tx-confirm">Your BT Yahoo! Mailbox</item>
        <item key="subject-tx-error">Email Transfer Error</item>
        <item key="subject-tx-start">Your new BT Yahoo! Mail account</item>
        <item key="tier">G</item>
       </hashref>
      </item>
      <item key="uk:plus:bt:pri:core:h">
       <hashref memory_address="0x8e73800">
        <item key="account">Master</item>
        <item key="path">/partners/bt/uk/tierH/</item>
        <item key="quota">P2</item>
        <item key="subject-tx-confirm">Your BT Yahoo! Mailbox</item>
        <item key="subject-tx-error">Email Transfer Error</item>
        <item key="subject-tx-start">Your new BT Yahoo! Mail account</item>
        <item key="tier">H</item>
       </hashref>
      </item>
      <item key="uk:plus:bt:sub:core:b">
       <hashref memory_address="0x8e715a0">
        <item key="account">Sub</item>
        <item key="path">/partners/bt/uk/tierB/</item>
        <item key="pop">P</item>
        <item key="quota">P0</item>
        <item key="subject-tx-confirm">Your BT Yahoo! Mailbox</item>
        <item key="subject-tx-error">Email Transfer Error</item>
        <item key="subject-tx-start">Your new BT Yahoo! Mail account</item>
        <item key="tier">B</item>
       </hashref>
      </item>
      <item key="uk:plus:bt:sub:core:c">
       <hashref memory_address="0x8e734c4">
        <item key="account">Sub</item>
        <item key="path">/partners/bt/uk/tierC/</item>
        <item key="pop">P</item>
        <item key="quota">P0</item>
        <item key="subject-tx-confirm">Your BT Yahoo! Internet mailbox</item>
        <item key="subject-tx-error">Email Transfer Error</item>
        <item key="subject-tx-start">Your new BT Yahoo! Internet account</item>
        <item key="tier">C</item>
       </hashref>
      </item>
      <item key="uk:plus:bt:sub:core:d">
       <hashref memory_address="0x8e735b4">
        <item key="account">Sub</item>
        <item key="path">/partners/bt/uk/tierD/</item>
        <item key="pop">P</item>
        <item key="quota">P0</item>
        <item key="subject-tx-confirm">Your BT Yahoo! Internet mailbox</item>
        <item key="subject-tx-error">Email Transfer Error</item>
        <item key="subject-tx-start">Your new BT Yahoo! Internet account</item>
        <item key="tier">D</item>
       </hashref>
      </item>
      <item key="uk:plus:bt:sub:core:e">
       <hashref memory_address="0x8e736a4">
        <item key="account">Sub</item>
        <item key="path">/partners/bt/uk/tierE/</item>
        <item key="pop">P</item>
        <item key="quota">P0</item>
        <item key="subject-tx-confirm">Your BT Yahoo! Broadband mailbox</item>
        <item key="subject-tx-error">Email Transfer Error</item>
        <item key="subject-tx-start">Your new BT Yahoo! Broadband account</item>
        <item key="tier">E</item>
       </hashref>
      </item>
      <item key="uk:plus:bt:sub:core:g">
       <hashref memory_address="0x8e73788">
        <item key="account">Sub</item>
        <item key="path">/partners/bt/uk/tierG/</item>
        <item key="pop">P</item>
        <item key="quota">P0</item>
        <item key="subject-tx-confirm">Your BT Yahoo! Mailbox</item>
        <item key="subject-tx-error">Email Transfer Error</item>
        <item key="subject-tx-start">Your new BT Yahoo! Mail account</item>
        <item key="tier">G</item>
       </hashref>
      </item>
      <item key="uk:plus:bt:sub:core:h">
       <hashref memory_address="0x8e757d8">
        <item key="account">Sub</item>
        <item key="path">/partners/bt/uk/tierH/</item>
        <item key="pop">P</item>
        <item key="quota">P0</item>
        <item key="subject-tx-confirm">Your BT Yahoo! Mailbox</item>
        <item key="subject-tx-error">Email Transfer Error</item>
        <item key="subject-tx-start">Your new BT Yahoo! Mail account</item>
        <item key="tier">H</item>
       </hashref>
      </item>
     </hashref>
    </item>
   </hashref>
  </item>
  <item key="cn_partner">
   <hashref memory_address="0x8e4bfb4">
   </hashref>
  </item>
  <item key="cti">
   <hashref memory_address="0x8e528f4">
    <item key="path">/partners/cti/</item>
    <item key="subject">Yahoo!</item>
   </hashref>
  </item>
  <item key="free">
   <hashref memory_address="0x8e52aec">
    <item key="SRV-header">allow=images;cg_sih=16;cg_sih_inv=16;cg_siu=http://mail.yimg.com/a/i/us/pim/ybang_16x16_1.gif;cg_siu_inv=http://mail.yimg.com/a/i/us/pim/ybang_16x16_dark_1.gif;cg_siw=16;cg_siw_inv=16;hih=16;hiu=http://mail.yimg.com/a/i/us/pim/ybang_16x16_1.gif;hiw=16;livewords=false;reportspam=generic;sih=16;</item>
    <item key="TIP-header">66.218.69.16</item>
    <item key="bypass-name-check">1</item>
    <item key="domain">
     <arrayref memory_address="0x8e52a44">
      <item key="0">y7mail.com</item>
      <item key="1">helloyahoo.com</item>
      <item key="2">rocketmail.com</item>
      <item key="3">ymail.com</item>
      <item key="4">kimo.com</item>
      <item key="5">maktoob.com</item>
